trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    wget https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
    unzip terraform_1.9.8_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
  displayName: Install Terraform

- task: AzureCLI@2
  displayName: Terraform Plan
  inputs:
    azureSubscription: 'terraform-connection1'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account show
      terraform init
      terraform validate
      terraform plan
